echo "Nettoyage de la base de données MongoDB..."
echo "Suppression des subscribers..."
sudo docker exec -it db mongosh open5gs --eval "db.subscribers.deleteMany({})"
echo "Suppression des gNBs..."
sudo docker exec -it db mongosh open5gs --eval "db.gnbs.deleteMany({})"
