services:
  
  ue-loadtester:
    image: "ghcr.io/borjis131/ue:v3.2.7"
    container_name: ue-loadtester
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      nproc: 65536
    volumes:
      - ../scripts/testing:/testing
      - ../config-files/ue/templates:/ue_templates
      - ../config-files/gnb/generated:/generated_gnbs
      - ../scripts/provisioning:/provisioning
    entrypoint: ["/bin/bash", "/provisioning/start_ues.sh"]
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    networks:
      - open5gs

  internet-sim:
    image: nginx:alpine
    container_name: internet-sim
    restart: unless-stopped
    networks:
      - open5gs
    volumes:
      - ../scripts/testing:/usr/share/nginx/html

networks:
  open5gs:
    external: true