mcc: '208'
mnc: '01'

nci: '0x000000010'
idLength: 32
tac: 1

linkIp: gnb1.ueransim.org
ngapIp: gnb1.ueransim.org
gtpIp: gnb1.ueransim.org

amfConfigs:
  - address: amf.open5gs.org
    port: 38412

slices:
  - sst: 1
    sd: 0x000001
  - sst: 2
    sd: 0x000001
  - sst: 3
    sd: 0x000001

ignoreStreamIds: true
