echo "Cleaning up the database..."
echo "Deleting subscribers..."
sudo docker exec -it db mongosh open5gs --eval "db.subscribers.deleteMany({})"
echo "Deleting gNBs..."
sudo docker exec -it db mongosh open5gs --eval "db.gnbs.deleteMany({})"
